payment:
  stripe:
    secret-key: sk_test_placeholder
    public-key: pk_test_placeholder
    webhook-secret: whsec_placeholder

  razorpay:
    key-id: rzp_test_placeholder
    secret-key: rzp_test_placeholder
    webhook-secret: whsec_placeholder

jwt:
  secret: biSATc5TwmekoReHTZyJfrgSHSWJljvcC8fSSKYp8v5b5vBRwuKihPEaDFVSkat7PyPSeMjURb29fYiCZ0vMlO
  expiration: 3600000
  refresh-expiration: 86400000
  remember-me-expiration: 2592000000
  prefix: Bearer
  header: Authorization
  token-type: Bearer

app:
  cookie:
    domain: localhost
    secure: false
  admin:
      email: ${ADMIN_EMAIL:admin@example.com}
      password: ${ADMIN_PASSWORD:Admin@1234}
      fullName: ${ADMIN_FULL_NAME:System Admin}